# Generated by Django 4.1 on 2023-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_hub", "0002_alter_task_options_alter_task_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(),
        ),
    ]
