# Generated by Django 4.1 on 2023-10-21 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_hub", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority", "deadline"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["position"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
    ]
